layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

social_media:
  # facebook: your_username
  # instagram: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # twitter: your_usernam
  website: https://plomeplomeplo.me Plôme
  website: https:www.highgroundproductions.ch High Ground Productions
  website: https://www.bandlab.com/yro0 Bandlab
  # website: http://your_website_url
  # youtube: your_username
