layout: sidebar
style: dark

plugins:
  - jekyll-octicons

  - jemoji



social_media:
  # facebook: your_username
  # instagram: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # twitter: your_usernam

 
  # website: http://your_website_url
  # youtube: your_username
